# Generated by Django 4.1 on 2025-07-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.team'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.activity'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.user'),
        ),
    ]
