# Generated by Django 4.1 on 2025-07-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_alter_leaderboard_team_alter_workout_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='leaderboard',
            table='leaderboard',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workout',
        ),
    ]
